### ISSUE TITLE
Can install under Python 3.5

### ISSUE THREAD

**Issue by ldng** [not-raspberry/pytest_reorder#1]
Packaging installed dependencies :
    setuptools>=21
    wheel>=0.29
    pip>=1.8

$ pip install pytest-reorder
```
Downloading/unpacking pytest-reorder
  Downloading pytest_reorder-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-mgyg_380/pytest-reorder/setup.py) egg_info for package pytest-reorder
    
Requirement already satisfied (use --upgrade to upgrade): pytest in ./build/tox/py35/lib/python3.5/site-packages (from pytest-reorder)
Installing collected packages: pytest-reorder
  Running setup.py install for pytest-reorder
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mgyg_380/pytest-reorder/setup.py", line 58, in <module>
        'pytest11': 'reorder=pytest_reorder.hook'
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 551, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    Complete output from command /home/user/project/build/tox/py35/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mgyg_380/pytest-reorder/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-htvlagnr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/project/build/tox/py35/include/site/python3.5:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/pytest_reorder

copying pytest_reorder/hook.py -> build/lib/pytest_reorder

copying pytest_reorder/__init__.py -> build/lib/pytest_reorder

copying pytest_reorder/reorder.py -> build/lib/pytest_reorder

running install_lib

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-mgyg_380/pytest-reorder/setup.py", line 58, in <module>

    'pytest11': 'reorder=pytest_reorder.hook'

  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/local/lib/python3.5/distutils/command/install.py", line 551, in run

    self.run_command(cmd_name)

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/local/lib/python3.5/distutils/dist.py", line 973, in run_command

    cmd_obj.ensure_finalized()

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options

    self.set_undefined_options('install',('install_layout','install_layout'))

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options

    setattr(self, dst_option, getattr(src_cmd_obj, src_option))

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__

    raise AttributeError(attr)

AttributeError: install_layout

----------------------------------------
Cleaning up...
Command /home/user/project/build/tox/py35/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mgyg_380/pytest-reorder/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-htvlagnr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/project/build/tox/py35/include/site/python3.5 failed with error code 1 in /tmp/pip-build-mgyg_380/pytest-reorder
Storing debug log for failure in /home/user/.pip/pip.log
```

Content of /home/user/.pip/pip.log
```
------------------------------------------------------------
/home/user/project/build/tox/py35/bin/pip run on Fri May 13 15:27:02 2016
Downloading/unpacking pytest-reorder
  Getting page https://pypi.python.org/simple/pytest-reorder/
  URLs to search for versions for pytest-reorder:
  * https://pypi.python.org/simple/pytest-reorder/
  Analyzing links from page https://pypi.python.org/simple/pytest-reorder/
    Found link https://pypi.python.org/packages/ea/51/050ecf04d75c300b4321fb5cf6c82206c5577d45edb0f9082942f759ecb5/pytest_reorder-0.1.0.tar.gz#md5=fa4952fd30376aa801ab647f80c5fb11 (from https://pypi.python.org/simple/pytest-reorder/), version: 0.1.0
  Downloading pytest_reorder-0.1.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/ea/51/050ecf04d75c300b4321fb5cf6c82206c5577d45edb0f9082942f759ecb5/pytest_reorder-0.1.0.tar.gz#md5=fa4952fd30376aa801ab647f80c5fb11 (from https://pypi.python.org/simple/pytest-reorder/)
  Running setup.py (path:/tmp/pip-build-mgyg_380/pytest-reorder/setup.py) egg_info for package pytest-reorder
    running egg_info
    creating pip-egg-info/pytest_reorder.egg-info
    writing pip-egg-info/pytest_reorder.egg-info/PKG-INFO
    writing requirements to pip-egg-info/pytest_reorder.egg-info/requires.txt
    writing dependency_links to pip-egg-info/pytest_reorder.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/pytest_reorder.egg-info/top_level.txt
    writing entry points to pip-egg-info/pytest_reorder.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/pytest_reorder.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/pytest_reorder.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/pytest_reorder.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-mgyg_380/pytest-reorder has version 0.1.0, which satisfies requirement pytest-reorder
  skipping extra tests
  skipping extra tests
  skipping extra tests
Requirement already satisfied (use --upgrade to upgrade): pytest in ./build/tox/py35/lib/python3.5/site-packages (from pytest-reorder)
Installing collected packages: pytest-reorder
  Running setup.py install for pytest-reorder
    Running command /home/user/project/build/tox/py35/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mgyg_380/pytest-reorder/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-htvlagnr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/project/build/tox/py35/include/site/python3.5
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/pytest_reorder
    copying pytest_reorder/hook.py -> build/lib/pytest_reorder
    copying pytest_reorder/__init__.py -> build/lib/pytest_reorder
    copying pytest_reorder/reorder.py -> build/lib/pytest_reorder
    running install_lib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mgyg_380/pytest-reorder/setup.py", line 58, in <module>
        'pytest11': 'reorder=pytest_reorder.hook'
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 551, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    Complete output from command /home/user/project/build/tox/py35/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mgyg_380/pytest-reorder/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-htvlagnr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/project/build/tox/py35/include/site/python3.5:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/pytest_reorder

copying pytest_reorder/hook.py -> build/lib/pytest_reorder

copying pytest_reorder/__init__.py -> build/lib/pytest_reorder

copying pytest_reorder/reorder.py -> build/lib/pytest_reorder

running install_lib

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-mgyg_380/pytest-reorder/setup.py", line 58, in <module>

    'pytest11': 'reorder=pytest_reorder.hook'

  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/local/lib/python3.5/distutils/command/install.py", line 551, in run

    self.run_command(cmd_name)

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/local/lib/python3.5/distutils/dist.py", line 973, in run_command

    cmd_obj.ensure_finalized()

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options

    self.set_undefined_options('install',('install_layout','install_layout'))

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options

    setattr(self, dst_option, getattr(src_cmd_obj, src_option))

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__

    raise AttributeError(attr)

AttributeError: install_layout

----------------------------------------
Cleaning up...
Command /home/user/project/build/tox/py35/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mgyg_380/pytest-reorder/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-htvlagnr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/project/build/tox/py35/include/site/python3.5 failed with error code 1 in /tmp/pip-build-mgyg_380/pytest-reorder
Exception information:
Traceback (most recent call last):
  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/user/project/build/tox/py35/lib/python3.5/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /home/user/project/build/tox/py35/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mgyg_380/pytest-reorder/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-htvlagnr-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/project/build/tox/py35/include/site/python3.5 failed with error code 1 in /tmp/pip-build-mgyg_380/pytest-reorder
```

**Comment by ldng** [comment]
Please disregard, it seems setuptools and pip weren't upgraded in the virtualenv. My mistake.

**Comment by not-raspberry** [comment]
Is seems more like a problem with `pip` than with the library.

Do you use virtualenv? What's your `pip` version? What's you version of `setuptools`? Maybe try upgrading them. The latest versions are more likely to work (or least likely to break... well, that's Python packaging).

I just attempted installing `pytest-reorder` under Python 3.5.1 from `pyenv` and it worked:
```
$ echo 3.5.1 > .python-version  # That's for pyenv
$ python --version
Python 3.5.1
$ virtualenv REPRO 
Using base prefix '/home/mp/.pyenv/versions/3.5.1'
New python executable in /home/mp/IDE/python/py3.5-repro/REPRO/bin/python3.5
Also creating executable in /home/mp/IDE/python/py3.5-repro/REPRO/bin/python
Installing setuptools, pip, wheel...done.
$ source ./REPRO/bin/activate
$ python --version
Python 3.5.1
$ pip --version
pip 8.1.2 from /home/mp/IDE/python/py3.5-repro/REPRO/lib/python3.5/site-packages (python 3.5)
$ pip install pytest-reorder --no-cache-dir
Collecting pytest-reorder
  Downloading pytest_reorder-0.1.0.tar.gz
Collecting pytest (from pytest-reorder)
  Downloading pytest-2.9.1-py2.py3-none-any.whl (161kB)
    100% |████████████████████████████████| 163kB 1.4MB/s 
Collecting py>=1.4.29 (from pytest->pytest-reorder)
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 1.3MB/s 
Installing collected packages: py, pytest, pytest-reorder
  Running setup.py install for pytest-reorder ... done
Successfully installed py-1.4.31 pytest-2.9.1 pytest-reorder-0.1.0
$ python
Python 3.5.1 (default, Apr 17 2016, 20:22:03) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytest_reorder import make_reordering_hook
>>> make_reordering_hook([r'a', None, r'b', r'c'])
<function make_reordering_hook.<locals>.pytest_collection_modifyitems at 0x7fe7c4c799d8>
>>> 
```

**Comment by not-raspberry** [comment]
@ldng  It seems we both hit the "Comment" button at the same moment. ACK, no problem, disregarding :)
